In [ ]:
import numpy as np

# Пример данных
X = np.array([[1, 2], [3, 4], [5, 6]])

# Центрирование данных
X_centered = X - np.mean(X, axis=0)

# Ручной расчет ковариационной матрицы
cov_matrix_manual = (X_centered.T @ X_centered) / X.shape[0]

print("Центрированные данные:")
print(X_centered)

print("Ковариационная матрица (ручной расчет):")
print(cov_matrix_manual)

# Ковариционная матрица с использованием np.cov
cov_matrix_np = np.cov(X.T)  # bias=True для полной ковариации

print("Ковариационная матрица (np.cov с bias=True):")
print(cov_matrix_np)

Центрированные данные:
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
Ковариационная матрица (ручной расчет):
[[2.66666667 2.66666667]
 [2.66666667 2.66666667]]
Ковариационная матрица (np.cov с bias=True):
[[4. 4.]
 [4. 4.]]
