https://stepik.org/lesson/1370101/step/5

Линейный дискриминант Фишера можно записать в виде:
$$
a(x) = argmax_{y∈Y}(x^T⋅α_y + β_y)
$$

где

$$
α_y = \hat Σ^{-1}⋅\hatμ_y
$$

$$
β_y = ln(λy⋅Py) - 0,5 ⋅ \hat μ_y^T ⋅ \hat Σ^ {-1} ⋅ \hat μ^y
$$

In [ ]:
import numpy as np

# исходные параметры распределений двух классов
np.random.seed(0)
mean1 = np.array([1, -2, 0])
mean2 = np.array([1, 3, 1])
r = 0.7
D = 2.0
V = [[D, D * r, D*r*r], [D*r, D, D*r], [D*r*r, D*r, D]] # три предиктора

# моделирование обучающей выборки
N = 1000
x1 = np.random.multivariate_normal(mean1, V, N).T
x2 = np.random.multivariate_normal(mean2, V, N).T

x_train = np.hstack([x1, x2]).T
y_train = np.hstack([np.zeros(N), np.ones(N)])

# вычисление оценок МО и общей ковариационной матрицы
mm1 = np.mean(x1.T, axis=0)
mm2 = np.mean(x2.T, axis=0)

a = np.hstack([(x1.T - mm1).T, (x2.T - mm2).T])
VV = np.array([
    [np.dot(a[0], a[0]) / (N*2-1), np.dot(a[0], a[1]) / (N*2-1), np.dot(a[0], a[2]) / (N*2-1)],
    [np.dot(a[1], a[0]) / (N*2-1), np.dot(a[1], a[1]) / (N*2-1), np.dot(a[1], a[2]) / (N*2-1)],
    [np.dot(a[2], a[0]) / (N*2-1), np.dot(a[2], a[1]) / (N*2-1), np.dot(a[2], a[2]) / (N*2-1)]
])

# параметры для линейного дискриминанта Фишера
Py1, L1 = 0.5, 1  # вероятности появления классов
Py2, L2 = 1 - Py1, 1  # и величины штрафов неверной классификации

# Функции:
alpha = lambda x, v, m: m @ np.linalg.inv(v)
beta = lambda x, v, m, l, py: np.log(l * py) - 0.5 * m @ np.linalg.inv(v) @ m
am = lambda x: np.argmax([alpha(x, VV, mm1) @ x.T + beta(x, VV, mm1, L1, Py1),
                          alpha(x, VV, mm2) @ x.T + beta(x, VV, mm2, L2, Py2)]) # классификатор

# Ответ на вопрос задания
alpha1, alpha2  = alpha(x_train, VV, mm1), alpha(x_train, VV, mm2)
beta1, beta2 = beta(x_train, VV, mm1, L1, Py1), beta(x_train, VV, mm2, L2, Py2)

# Предсказание по модели
predict = [am(x) for x in x_train]

# Качество
Q = sum(predict != y_train)

(array([ 2.36511519, -3.65174678,  1.40519463]),
 array([-1.09197193,  3.10341471, -1.09191239]))

In [ ]:
# @title Вычисление матрицы ковариации вручную
# исходные параметры распределений двух классов
np.random.seed(0)
mean1 = np.array([1, -2, 0])
mean2 = np.array([1, 3, 1])
r = 0.7
D = 2.0
V = [[D, D * r, D*r*r], [D*r, D, D*r], [D*r*r, D*r, D]] # три предиктора

# моделирование обучающей выборки
N = 1000
x1 = np.random.multivariate_normal(mean1, V, N).T
x2 = np.random.multivariate_normal(mean2, V, N).T

x_train = np.hstack([x1, x2]).T
y_train = np.hstack([np.zeros(N), np.ones(N)])

# вычисление оценок МО и общей ковариационной матрицы
mm1 = np.mean(x1.T, axis=0)
mm2 = np.mean(x2.T, axis=0)

a = np.hstack([(x1.T - mm1).T, (x2.T - mm2).T])
VV_manual = np.array([
    [np.dot(a[0], a[0]) / (N*2-1), np.dot(a[0], a[1]) / (N*2-1), np.dot(a[0], a[2]) / (N*2-1)],
    [np.dot(a[1], a[0]) / (N*2-1), np.dot(a[1], a[1]) / (N*2-1), np.dot(a[1], a[2]) / (N*2-1)],
    [np.dot(a[2], a[0]) / (N*2-1), np.dot(a[2], a[1]) / (N*2-1), np.dot(a[2], a[2]) / (N*2-1)]
])

# Проверка
data = np.vstack([x1.T - mm1, x2.T - mm2])
VV = np.cov(data.T)

VV_manual == VV

# Проверка равенства
is_equal = np.allclose(VV_manual, VV)

print("Матрица ковариации вручную:\n", VV_manual)
print("Ожидаемая матрица ковариации:\n", VV)
print("Равенство:", is_equal)

Матрица ковариации вручную:
 [[1.91375482 1.32262886 0.90497381]
 [1.32262886 1.9039018  1.31898097]
 [0.90497381 1.31898097 1.9172694 ]]
Ожидаемая матрица ковариации:
 [[1.91375482 1.32262886 0.90497381]
 [1.32262886 1.9039018  1.31898097]
 [0.90497381 1.31898097 1.9172694 ]]
Равенство: True


In [ ]:
# Виталий Золотов https://stepik.org/lesson/1370101/step/5?discussion=10354853&thread=solutions&unit=1386291
import numpy as np

np.random.seed(0)

# Исходные параметры распределений двух классов
mean1 = np.array([1, -2, 0])
mean2 = np.array([1, 3, 1])
r = 0.7
D = 2.0
V = [[D, D * r, D*r*r], [D*r, D, D*r], [D*r*r, D*r, D]]

# Моделирование обучающей выборки
N = 1000
x1 = np.random.multivariate_normal(mean1, V, N).T
x2 = np.random.multivariate_normal(mean2, V, N).T

# Объединение выборок
x_train = np.hstack([x1, x2]).T
y_train = np.hstack([np.zeros(N), np.ones(N)])

# Вычисление оценок математического ожидания и ковариационной матрицы
mu1 = np.mean(x1.T, axis=0)  # Математическое ожидание для класса 0
mu2 = np.mean(x2.T, axis=0)  # Математическое ожидание для класса 1

# Объединяем центрированные данные
data = np.vstack([x1.T - mu1, x2.T - mu2])

# Вычисляем ковариационную матрицу
VV = np.cov(data.T)

# Обратная ковариационная матрица
Sigma_inv = np.linalg.inv(VV)

# Параметры для дискриминанта Фишера
P_y1 = 0.5  # априорная вероятность класса 0
P_y2 = 1 - P_y1  # априорная вероятность класса 1
lambda_y1, lambda_y2 = 1, 1  # величины штрафов неверной классификации

# Вычисление d1 и d2 для всех обучающих образцов
alpha1 = Sigma_inv @ mu1
alpha2 = Sigma_inv @ mu2
beta1 = np.log(lambda_y1 * P_y1) - 0.5 * mu1 @ Sigma_inv @ mu1
beta2 = np.log(lambda_y2 * P_y2) - 0.5 * mu2 @ Sigma_inv @ mu2
d1 = x_train @ alpha1 + beta1
d2 = x_train @ alpha2 + beta2